### ISSUE TITLE
Error Running Builder

### ISSUE THREAD

**Issue by jkellett** [palantir/eclipse-tslint#12]
Hi, I have just installed eclipse-tslint and see the error below. I have tried different .ts files but always the same result.

The typescript builder is enabled and working fine.

eclipse.buildId=4.4.2.M20150204-1700
java.version=1.7.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

com.palantir.tslint
Error
Sun Mar 08 12:12:05 GMT 2015
Errors running builder 'TSLint Project Builder' on project 'tstest'.

java.lang.RuntimeException: The following request caused an error to be thrown:
{"method":"lint","arguments":["C:\\Users\\kellett\\workspace-ts\\tstest\\ts\\Test.ts"]}
TypeError: Cannot read property 'getFullWidth' of undefined
	at EnableDisableRulesWalker.RuleWalker (C:\Users\kellett\Apps\eclipse-ts\plugins\com.palantir.tslint_1.0.1.v20150202-2346
ode_modules\tslint\lib\tslint.js:26770:41)
	at new EnableDisableRulesWalker (C:\Users\kellett\Apps\eclipse-ts\plugins\com.palantir.tslint_1.0.1.v20150202-2346
ode_modules\tslint\lib\tslint.js:27023:20)
	at Linter.lint (C:\Users\kellett\Apps\eclipse-ts\plugins\com.palantir.tslint_1.0.1.v20150202-2346
ode_modules\tslint\lib\tslint.js:27200:31)
	at LinterEndpoint.lint (C:\Users\kellett\Apps\eclipse-ts\plugins\com.palantir.tslint_1.0.1.v20150202-2346\bin\bridge.js:19:33)
	at Main.processRequest (C:\Users\kellett\Apps\eclipse-ts\plugins\com.palantir.tslint_1.0.1.v20150202-2346\bin\bridge.js:52:37)
	at Interface.<anonymous> (C:\Users\kellett\Apps\eclipse-ts\plugins\com.palantir.tslint_1.0.1.v20150202-2346\bin\bridge.js:39:23)
	at Interface.emit (events.js:107:17)
	at Interface._onLine (readline.js:214:10)
	at Interface.<anonymous> (readline.js:344:12)
	at Array.forEach (native)
	at com.palantir.tslint.services.Bridge.processRequest(Bridge.java:132)
	at com.palantir.tslint.services.Bridge.call(Bridge.java:85)
	at com.palantir.tslint.services.Bridge.call(Bridge.java:73)
	at com.palantir.tslint.Linter.lint(Linter.java:69)
	at com.palantir.tslint.Builder.lint(Builder.java:93)
	at com.palantir.tslint.Builder.access$0(Builder.java:76)
	at com.palantir.tslint.Builder$DeltaVisitor.visit(Builder.java:118)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:69)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:49)
	at com.palantir.tslint.Builder.incrementalBuild(Builder.java:73)
	at com.palantir.tslint.Builder.build(Builder.java:56)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by ashwinr** [comment]
hm, strange. do you have a snippet of the typescript file that's causing this exception?

**Comment by jkellett** [comment]
Hi there, same result even on a project with a single ts file containing a single line "var a = 10;"

**Comment by ashwinr** [comment]
do you have tslint.json in the right path as specified here: https://github.com/palantir/eclipse-tslint#configuration-file

**Comment by jkellett** [comment]
Yes, config is correct I think.

I've had a poke about in the code...

I can see that in function getSourceFile (around line 7143) the filename passed in is "C:\ts\Test.ts"

This is then looked up in filesByName but the entries there are like this "C:/ts/Test.ts" and the lookup fails since the slashes are different.

**Comment by felixcontant** [comment]
I also have the issue. It used to work before I updated to Eclipse Luna. I have a tslint.json file at the root of my project.

-Eclipse Version: Luna Release (4.4.0)
Build id: 20140612-0600
-TSLint 1.0.1.v20150202-2346	

Errors occurred during the build.
Errors running builder 'TSLint Project Builder' on project 'ui'.
The following request caused an error to be thrown:
{"method":"lint","arguments":["C:\\path\\to\\my\\file\\filename.ts"]}
TypeError: Cannot call method 'getFullWidth' of undefined
	at EnableDisableRulesWalker.RuleWalker (C:\dev\eclipse-typescript\configuration\org.eclipse.osgi\121\data\-1033652861\plugins\com.palantir.tslint_1.0.1.v20150202-2346
ode_modules\tslint\lib\tslint.js:26770:42)
	at new EnableDisableRulesWalker (C:\dev\eclipse-typescript\configuration\org.eclipse.osgi\121\data\-1033652861\plugins\com.palantir.tslint_1.0.1.v20150202-2346
ode_modules\tslint\lib\tslint.js:27023:20)
	at Linter.lint (C:\dev\eclipse-typescript\configuration\org.eclipse.osgi\121\data\-1033652861\plugins\com.palantir.tslint_1.0.1.v20150202-2346
ode_modules\tslint\lib\tslint.js:27200:31)
	at LinterEndpoint.lint (C:\dev\eclipse-typescript\configuration\org.eclipse.osgi\121\data\-1033652861\plugins\com.palantir.tslint_1.0.1.v20150202-2346\bin\bridge.js:19:33)
	at Main.processRequest (C:\dev\eclipse-typescript\configuration\org.eclipse.osgi\121\data\-1033652861\plugins\com.palantir.tslint_1.0.1.v20150202-2346\bin\bridge.js:52:37)
	at Interface.<anonymous> (C:\dev\eclipse-typescript\configuration\org.eclipse.osgi\121\data\-1033652861\plugins\com.palantir.tslint_1.0.1.v20150202-2346\bin\bridge.js:39:23)
	at Interface.emit (events.js:95:17)
	at Interface._onLine (readline.js:202:10)
	at Interface.<anonymous> (readline.js:322:12)
	at Array.forEach (native)

**Comment by everbeek** [comment]
This is likely related, and resolved, and has to do with file path normalization on windows:

https://github.com/palantir/tslint/issues/288

**Comment by felixcontant** [comment]
@everbeek Thanks, it worked for me.

**Comment by jkellett** [comment]
Also working for me when I manually patch the plugin files.

Thanks a lot :)

**Comment by ashwinr** [comment]
closing -- latest tslint release should have this.
