### ISSUE TITLE
While select Configure-Enable TSLint Builder.

### ISSUE THREAD

**Issue by jery-Shen** [palantir/eclipse-tslint#28]
Errors occurred during the build.
Errors running builder 'TSLint Project Builder' on project 'qccweb'.
The following request caused an error to be thrown:
{"method":"lint","arguments":["/Users/shenyaojie/Sites/qccweb/e2e/app.e2e-spec.ts"]}
Error: Could not find the following rules specified in the configuration:
arrow-return-shorthand
callable-types
import-blacklist
import-spacing
interface-over-type-literal
no-duplicate-super
no-empty-interface
no-misused-new
no-non-null-assertion
no-string-throw
no-unnecessary-initializer
prefer-const
typeof-compare
unified-signatures
directive-selector
component-selector
use-input-property-decorator
use-output-property-decorator
use-host-property-decorator
no-input-rename
no-output-rename
use-life-cycle-interface
use-pipe-transform-interface
component-class-suffix
directive-class-suffix
no-access-missing-member
templates-use-public
invoke-injectable
	at Object.loadRules (/Applications/Eclipse.app/Contents/Eclipse/plugins/com.palantir.tslint_1.0.1.v20160225-1827/node_modules/tslint/lib/ruleLoader.js:29:15)
	at Linter.lint (/Applications/Eclipse.app/Contents/Eclipse/plugins/com.palantir.tslint_1.0.1.v20160225-1827/node_modules/tslint/lib/tslint.js:24:44)
	at LinterEndpoint.lint (/Applications/Eclipse.app/Contents/Eclipse/plugins/com.palantir.tslint_1.0.1.v20160225-1827/bin/bridge.js:17:33)
	at Main.processRequest (/Applications/Eclipse.app/Contents/Eclipse/plugins/com.palantir.tslint_1.0.1.v20160225-1827/bin/bridge.js:46:37)
	at Interface.<anonymous> (/Applications/Eclipse.app/Contents/Eclipse/plugins/com.palantir.tslint_1.0.1.v20160225-1827/bin/bridge.js:36:23)
	at emitOne (events.js:115:13)
	at Interface.emit (events.js:210:7)
	at Interface._onLine (readline.js:278:10)
	at Interface._normalWrite (readline.js:419:12)
	at Socket.ondata (readline.js:138:10)

**Comment by thibaut38410** [comment]
I have the same issue. have you found a solution ?

**Comment by martinwalke** [comment]
I know this is old but we had this and it was due to the fact that there was a _tslint.json_ file already existing. Delete that one first.

**Comment by malakeel** [comment]
This does not solve the problem at all. tslint.json file needs to exist in the top level directory. If deleted will get an error as well.
